env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - airbnb
  - airbnb/hooks
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  no-use-before-define: 0 # https://stackoverflow.com/questions/63818415/react-was-used-before-it-was-defined/64024916#64024916
  "@typescript-eslint/no-use-before-define": error
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  react/jsx-props-no-spreading: off
  react/jsx-filename-extension:
    - warn
    - extensions:
        - '.tsx'
  react/jsx-one-expression-per-line: off
  react/jsx-uses-react: off # https://ja.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
  react/prop-types: off
  react/react-in-jsx-scope: off
  import/prefer-default-export: off
  import/extensions:
    - error
    - always
    - ts: never
      tsx: never
  import/order: # sort to import clause
    - error
    - newlines-between: never
      alphabetize:
        order: asc
settings:
  import/parsers:
    '@typescript-eslint/parser': ['ts', 'tsx']
  import/resolver:
    typescript:
      alwaysTryTypes: true
