env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - airbnb
  - airbnb/hooks
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/react-in-jsx-scope: off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  import/order: # sort to import clause
    - error
    - newlines-between: never
      alphabetize:
        order: asc
  react/jsx-props-no-spreading: off
  react/jsx-filename-extension:
    - warn
    - extensions:
      - '.tsx'
  import/prefer-default-export: off
  import/extensions:
    - error
    - always
    - ts: never
      tsx: never
  react/jsx-one-expression-per-line: off
settings:
  import/parsers:
    '@typescript-eslint/parser': ['ts', 'tsx']
  import/resolver:
    typescript:
      alwaysTryTypes: true
